In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# import scienceplots

# plt.style.use('science')

In [5]:
df = pd.read_excel("./datafeatures_all.xlsx") 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359 entries, 0 to 358
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        359 non-null    datetime64[ns]
 1   Contest number              359 non-null    int64
 2   Word                        359 non-null    object
 3   Number of reported results  359 non-null    int64
 4   Number in hard mode         359 non-null    int64
 5   1 try                       359 non-null    int64
 6   2 tries                     359 non-null    int64
 7   3 tries                     359 non-null    int64
 8   4 tries                     359 non-null    int64
 9   5 tries                     359 non-null    int64
 10  6 tries                     359 non-null    int64
 11  7 or more tries (X)         359 non-null    int64
 12  Etrial                      359 non-null    float64
 13  weekday                     359 non-null    int64
 14  HD_ratio                    359 non-null    float64
 15  double                      359 non-null    float64
 16  trible                      359 non-null    float64
 17  double_space                359 non-null    float64
 18  begin                       359 non-null    float64
 19  end                         359 non-null    float64
 20  duplicate                   359 non-null    int64
 21  freq                        359 non-null    float64
 22  freq_weig                   359 non-null    float64
 23  duplicate_con               359 non-null    int64
 24  vowel_num                   359 non-null    int64
 25  vowel_begin                 359 non-null    int64
 26  num_phonemes                359 non-null    int64
dtypes: datetime64[ns](1), float64(9), int64(16), object(1)
memory usage: 75.9+ KB

In [6]:
df

,Date,Contest number,Word,Number of reported results,Number in hard mode,1 try,2 tries,3 tries,4 tries,5 tries,...,double_space,begin,end,duplicate,freq,freq_weig,duplicate_con,vowel_num,vowel_begin,num_phonemes
0,2022-01-07,202,slump,80630,1362,1,3,23,39,24,...,-0.725907,1.964358,-1.271214,0,0.461317,0.511157,0,1,0,5
1,2022-01-08,203,crank,101503,1763,1,5,23,31,24,...,-0.725907,0.659900,-0.923738,0,0.520873,0.557551,0,1,0,5
2,2022-01-09,204,gorge,91477,1913,1,3,13,27,30,...,-0.725907,-0.499618,1.552025,0,0.555048,0.580078,0,2,0,3
3,2022-01-10,205,query,107134,2242,1,4,16,30,30,...,-0.725907,-1.514197,0.509598,0,0.499582,0.502362,0,2,0,5
4,2022-01-11,206,drink,153880,3017,1,9,35,34,16,...,-0.725907,-0.861968,-0.923738,0,0.479670,0.510066,0,1,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,2022-12-27,556,condo,20879,2012,0,2,17,35,29,...,-0.725907,0.659900,-1.140910,0,0.516578,0.553540,0,2,0,5
355,2022-12-28,557,impel,20160,1937,0,3,21,40,25,...,-0.725907,-1.006908,-0.576262,0,0.536677,0.587237,0,2,1,5
356,2022-12-29,558,havoc,20001,1919,0,2,16,38,30,...,0.235364,-0.934438,-1.401517,0,0.505127,0.542356,0,2,0,5
357,2022-12-30,559,molar,21204,1973,0,4,21,38,26,...,-0.725907,-0.282209,-0.098484,0,0.574771,0.600835,0,2,0,4
358,2022-12-31,560,manly,20380,1899,0,2,17,37,29,...,-0.725907,-0.282209,0.509598,0,0.514416,0.543383,0,1,0,5

In [11]:
for i in range(15, 27):
    print(i)
    print(np.corrcoef(np.diff(df.iloc[:, i]), np.diff(df["Etrial"]))[0, 1])

15
-0.09740045869541628
16
-0.12352229509644709
17
0.012430067164920703
18
-0.2080324549647681
19
0.001996594353251545
20
0.22548088924483134
21
-0.2798578629302742
22
-0.28303273626618985
23
0.22548088924483134
24
-0.09559183208902818
25
-0.02481444031029015
26
0.05717158961572103